services:
  db:
    image: postgres:17.4
    container_name: postgres_db 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 100

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal

  inventory:
    build:
      context: .
      dockerfile: ./apps/inventory/Dockerfile
    container_name: inventory
    depends_on:
      - db
    networks:
      - internal
  
  orders:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    container_name: orders
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:

volumes:
  postgres_data:


